### ISSUE TITLE
Контест 9 - двоичные деревья поиска

### ISSUE THREAD

**Issue by tkhirianov** [mipt-cs/course-site-python3#39]
Контест: двоичные дервья поиска
Ответственный: Семенцов-Огиевский

Задачи можно смотреть тут: https://server.179.ru/tasks/python/2017b1/pgm32__Graphs-1.html
и тут (для Си): http://93.175.29.65/cgi-bin/new-client?contest_id=600009

**Comment by tkhirianov** [comment]
Контест по графам вытащен на Си тут:
https://github.com/mipt-cs-on-python3/contests/blob/master/judge_mipt_ru/tree_contest.tgz

**Comment by senya** [comment]
готова A - btree_add_print - https://github.com/mipt-cs-on-python3/problembook/tree/master/problems/graphs/btree/btree_add_print

**Comment by senya** [comment]
давно это было но думается мне я все сделал..
