### ISSUE TITLE
Практика 5 — замечания

### ISSUE THREAD

**Issue by fufler** [mipt-cs/course-site-python3#8]
Нужно переименовать работу, потому что её текущее название никак не соответствует сути.

**Comment by tkhirianov** [comment]
Переименовал все работы, не только пятую. Зальёшь на сайт?

**Comment by fufler** [comment]
Совершенно неожиданно в тексте работы встречается построение гистограмм, хотя построению графиков посвящена отдельная работа. Нужно исправить.

**Comment by tkhirianov** [comment]
Wontfix.
